version: '3.8'

services:
    web:
        container_name: web
        build: ./web/
        ports:
         - "80:80"
        environment:
          - TELEGRAM_API_TOKEN=1198378294:AAFmuBaTdJ-A1nUsntRKe-X8lqsfnRBo3SU

        command: uvicorn main:app --host 0.0.0.0 --port 80