FROM python:3.9.13-slim

RUN mkdir app
WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./app/ .
COPY ./requirements.txt .

RUN pip install -U pip \
    && pip install --no-cache-dir -r requirements.txt
